name: Build and Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Edit package.json
        run: npx json -I -f package.json -e 'this.homepage="${{ secrets.DEV_HOMEPAGE_URL }}"'

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          FALLBACK_CHAIN_ID: ${{ secrets.DEV_FALLBACK_CHAIN_ID }}
          SUPPORTED_CHAIN_IDS: ${{ secrets.DEV_SUPPORTED_CHAIN_IDS }}
          DATA_PROVIDER_ADDRESSES: ${{ secrets.DEV_DATA_PROVIDER_ADDRESSES }}
          LENDING_POOL_ADDRESSES: ${{ secrets.DEV_LENDING_POOL_ADDRESSES }}
          INFURA_API_KEY: ${{ secrets.DEV_INFURA_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.DEV_ALCHEMY_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.DEV_ETHERSCAN_API_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: ${{ secrets.DEV_DEPLOY_REPOSITORY_NAME }}
          ssh-key: ${{ secrets.DEV_DEPLOY_KEY }}
          branch: gh-pages
          folder: dist
          clean: true
